runtime: custom  # to use with docker
env: flex
entrypoint: gunicorn -b :$PORT app:app
# entrypoint: python3 python_app/app.py

runtime_config:
  python_version: 3

# settings are to reduce cost on flexible environment
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
