runtime: python37


# Following suggestions from  https://cloud.google.com/source-repositories/docs/quickstart
# and https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard_python37/hello_world
