steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project=$PROJECT_ID']

# from https://cloud.google.com/source-repositories/docs/quickstart-triggering-builds-with-source-repositories
